### ISSUE TITLE
Label not created and if exists in project does not add to issue

### ISSUE THREAD

**Issue by menkaff** [Wyox/laravel-gitlab-reporter#1]
Hi @Wyox 
Thanks for awesome repository , with reporter token in gitlab it does not create labels and even does not add created labels to an issue

**Comment by Wyox** [comment]
Hi, I haven't had much time to check this on an earlier notice, but your objective here seems to create or report an issue with custom labels within your code?

**Comment by menkaff** [comment]
Hi,Yes I want to make labes with custom objects although default labels were not working

**Comment by Wyox** [comment]
I've changed some code to allow custom labels and fix current labels if they are set using the config. If you update to version 1.1.1 it should all be fixed! Thanks for your help
