### ISSUE TITLE
PHP 8 

### ISSUE THREAD

**Issue by menkaff** [Wyox/laravel-gitlab-reporter#3]
I want to install this package for laravel 8 (sail) that uses PHP 8 but it throws these lines of error 
` Problem 1
    - php-http/guzzle6-adapter[dev-master, v2.0.2] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - php-http/guzzle6-adapter[v2.0.0, ..., v2.0.1] require php ^7.1 -> your php version (8.0.3) does not satisfy that requirement.
    - wyox/laravel-gitlab-reporter dev-master requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1, v2.0.2, 2.x-dev (alias of dev-master)].
    - php-http/guzzle6-adapter 2.x-dev is an alias of php-http/guzzle6-adapter dev-master and thus requires it to be installed too.
    - Root composer.json requires wyox/laravel-gitlab-reporter dev-master -> satisfiable by wyox/laravel-gitlab-reporter[dev-master].`

**Comment by Wyox** [comment]
Probably really late to comment on this issue however I've published a v2.0.0 that now works with Laravel 9 and newer which should work with PHP 8.0 -> PHP 8.3
